pre-release-commit-message = "chore: Release mockd v{{version}}"
tag-message = "{{tag_name}}"
tag-name = "mockd-v{{version}}"
pre-release-hook = ["./release-hook.sh"]
pre-release-replacements = [
    { file = "README.md", search = "mockd = \"\\d+\\.\\d+\\.\\d+\"", replace = "mockd = \"{{version}}\"", exactly = 1 },
    { file = "src/lib.rs", search = "mockd = \"\\d+\\.\\d+\\.\\d+\"", replace = "mockd = \"{{version}}\"", exactly = 1 },
]
